### ISSUE TITLE
Bird colour

### ISSUE THREAD

**Issue by Moorst** [after12am/boids.js#15]
Is it possible to change the birds' colour without messing with the boids.js file?

**Comment by after12am** [comment]
Hi Moorst,

I added colorable function to Bird class.
http://after12am.github.io/boids.js/colorize.html

Here is example.
https://github.com/after12am/boids.js/blob/master/example/app/scripts/colorize.js

Is this ok?

**Comment by after12am** [comment]
And I fixed problem not to set default position. https://github.com/after12am/boids.js/commit/4b8c385c7b6656e1f40486e3f5252e976d65ad20

I am sorry about these problem...

**Comment by after12am** [comment]
fix

**Comment by Moorst** [comment]
Thanks!
